In [1]:
from connectors.query_log.extract import QueryLogExtractor
from connectors.query_log.utils import parse_bigquery_query_log_json
import sqlglot

In [2]:
file_path = "datasets/bigquery_query_logs.json"

In [3]:
parsed = parse_bigquery_query_log_json(file_path)

In [4]:
parsed['table_info']

        project_id      dataset_id     table_id
0  ai-field-alex-g  demo_ecommerce       orders
1  ai-field-alex-g  demo_ecommerce    customers
2  ai-field-alex-g  demo_ecommerce     products
3  ai-field-alex-g  demo_ecommerce  order_items

In [5]:
qle = QueryLogExtractor()

In [6]:
res = qle.extract_info_from_query_log_json(file_path, cache=True)

In [7]:
res.get("query_info")

,project_id,query,query_id
0,ai-field-alex-g,"SELECT o.order_id, oi.order_item_id, p.product...",5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
1,ai-field-alex-g,"SELECT c.customer_name, SUM(o.total_amount) AS...",37d8ba5a578612485b6ea4016431b4eee13b52d98d3bdd...
2,ai-field-alex-g,"SELECT c.customer_id, c.customer_name, o.order...",349b2a6b9c908efa0b78d8dfab3bcc98440a801589de2c...
3,ai-field-alex-g,"SELECT p.product_id, p.product_name, SUM(oi.qu...",c5e2381771d25a9aaf71fcdc8a26d2378bad8f412b2a60...

In [8]:
qle.query_info

,project_id,query,query_id
0,ai-field-alex-g,"SELECT o.order_id, oi.order_item_id, p.product...",5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
1,ai-field-alex-g,"SELECT c.customer_name, SUM(o.total_amount) AS...",37d8ba5a578612485b6ea4016431b4eee13b52d98d3bdd...
2,ai-field-alex-g,"SELECT c.customer_id, c.customer_name, o.order...",349b2a6b9c908efa0b78d8dfab3bcc98440a801589de2c...
3,ai-field-alex-g,"SELECT p.product_id, p.product_name, SUM(oi.qu...",c5e2381771d25a9aaf71fcdc8a26d2378bad8f412b2a60...

In [9]:
qle.database_info

0    ai-field-alex-g
Name: project_id, dtype: str

In [10]:
qle.schema_info

        project_id                      dataset_id
0  ai-field-alex-g  ai-field-alex-g.demo_ecommerce

In [11]:
qle.table_info

,project_id,dataset_id,table_id
0,ai-field-alex-g,ai-field-alex-g.demo_ecommerce,ai-field-alex-g.demo_ecommerce.orders
1,ai-field-alex-g,ai-field-alex-g.demo_ecommerce,ai-field-alex-g.demo_ecommerce.order_items
2,ai-field-alex-g,ai-field-alex-g.demo_ecommerce,ai-field-alex-g.demo_ecommerce.products
3,ai-field-alex-g,ai-field-alex-g.demo_ecommerce,ai-field-alex-g.demo_ecommerce.customers

In [12]:
qle.column_info.head()

,query_id,table_id,table_name,column_id,column_name
0,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...,ai-field-alex-g.demo_ecommerce.orders,orders,ai-field-alex-g.demo_ecommerce.orders.order_id,order_id
1,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...,ai-field-alex-g.demo_ecommerce.order_items,order_items,ai-field-alex-g.demo_ecommerce.order_items.ord...,order_item_id
2,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...,ai-field-alex-g.demo_ecommerce.products,products,ai-field-alex-g.demo_ecommerce.products.produc...,product_name
3,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...,ai-field-alex-g.demo_ecommerce.order_items,order_items,ai-field-alex-g.demo_ecommerce.order_items.qua...,quantity
4,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...,ai-field-alex-g.demo_ecommerce.order_items,order_items,ai-field-alex-g.demo_ecommerce.order_items.price,price

In [13]:
qle._cache.get("column_references_info")

,left_table_name,left_table_id,left_table_alias,left_column_name,left_column_id,right_table_name,right_table_id,right_table_alias,right_column_name,right_column_id,criteria
0,order_items,ai-field-alex-g.demo_ecommerce.order_items,oi,order_id,ai-field-alex-g.demo_ecommerce.order_items.ord...,orders,ai-field-alex-g.demo_ecommerce.orders,o,order_id,ai-field-alex-g.demo_ecommerce.orders.order_id,o.order_id = oi.order_id
1,products,ai-field-alex-g.demo_ecommerce.products,p,product_id,ai-field-alex-g.demo_ecommerce.products.produc...,order_items,ai-field-alex-g.demo_ecommerce.order_items,oi,product_id,ai-field-alex-g.demo_ecommerce.order_items.pro...,oi.product_id = p.product_id
2,orders,ai-field-alex-g.demo_ecommerce.orders,o,customer_id,ai-field-alex-g.demo_ecommerce.orders.customer_id,customers,ai-field-alex-g.demo_ecommerce.customers,c,customer_id,ai-field-alex-g.demo_ecommerce.customers.custo...,c.customer_id = o.customer_id
3,orders,ai-field-alex-g.demo_ecommerce.orders,o,customer_id,ai-field-alex-g.demo_ecommerce.orders.customer_id,customers,ai-field-alex-g.demo_ecommerce.customers,c,customer_id,ai-field-alex-g.demo_ecommerce.customers.custo...,c.customer_id = o.customer_id
4,order_items,ai-field-alex-g.demo_ecommerce.order_items,oi,product_id,ai-field-alex-g.demo_ecommerce.order_items.pro...,products,ai-field-alex-g.demo_ecommerce.products,p,product_id,ai-field-alex-g.demo_ecommerce.products.produc...,p.product_id = oi.product_id

In [14]:
qle.column_references_info.head()

,left_table_id,left_table_name,left_column_id,left_column_name,right_table_id,right_table_name,right_column_id,right_column_name,criteria
0,ai-field-alex-g.demo_ecommerce.order_items,order_items,ai-field-alex-g.demo_ecommerce.order_items.ord...,order_id,ai-field-alex-g.demo_ecommerce.orders,orders,ai-field-alex-g.demo_ecommerce.orders.order_id,order_id,o.order_id = oi.order_id
1,ai-field-alex-g.demo_ecommerce.products,products,ai-field-alex-g.demo_ecommerce.products.produc...,product_id,ai-field-alex-g.demo_ecommerce.order_items,order_items,ai-field-alex-g.demo_ecommerce.order_items.pro...,product_id,oi.product_id = p.product_id
2,ai-field-alex-g.demo_ecommerce.orders,orders,ai-field-alex-g.demo_ecommerce.orders.customer_id,customer_id,ai-field-alex-g.demo_ecommerce.customers,customers,ai-field-alex-g.demo_ecommerce.customers.custo...,customer_id,c.customer_id = o.customer_id
4,ai-field-alex-g.demo_ecommerce.order_items,order_items,ai-field-alex-g.demo_ecommerce.order_items.pro...,product_id,ai-field-alex-g.demo_ecommerce.products,products,ai-field-alex-g.demo_ecommerce.products.produc...,product_id,p.product_id = oi.product_id

In [ ]:
from connectors.query_log.utils import parse_sql_query
import pandas as pd
from sqlglot.expressions import Join, From, Table, Column

In [8]:
res["query_info"]

,project_id,query,query_id
0,ai-field-alex-g,"SELECT o.order_id, oi.order_item_id, p.product...",5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
1,ai-field-alex-g,"SELECT c.customer_name, SUM(o.total_amount) AS...",37d8ba5a578612485b6ea4016431b4eee13b52d98d3bdd...
2,ai-field-alex-g,"SELECT c.customer_id, c.customer_name, o.order...",349b2a6b9c908efa0b78d8dfab3bcc98440a801589de2c...
3,ai-field-alex-g,"SELECT p.product_id, p.product_name, SUM(oi.qu...",c5e2381771d25a9aaf71fcdc8a26d2378bad8f412b2a60...

In [9]:
res["query_info"]["query_id"].iloc[0]

'5207e6b0fe644251a1456568f465b2a760d2f03f05adc2236244edb9acbcc05a'

In [10]:
parsed_dict = parse_sql_query(res["query_info"]["query"].iloc[0], res["query_info"]["query_id"].iloc[0], "bigquery")

In [11]:
parsed_dict["column_info"]

,table_alias,table_name,column_name,table_id,column_id,query_id
0,o,orders,order_id,ai-field-alex-g.demo_ecommerce.orders,ai-field-alex-g.demo_ecommerce.orders.order_id,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
1,oi,order_items,order_item_id,ai-field-alex-g.demo_ecommerce.order_items,ai-field-alex-g.demo_ecommerce.order_items.ord...,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
2,p,products,product_name,ai-field-alex-g.demo_ecommerce.products,ai-field-alex-g.demo_ecommerce.products.produc...,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
3,oi,order_items,quantity,ai-field-alex-g.demo_ecommerce.order_items,ai-field-alex-g.demo_ecommerce.order_items.qua...,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
4,oi,order_items,price,ai-field-alex-g.demo_ecommerce.order_items,ai-field-alex-g.demo_ecommerce.order_items.price,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
5,o,orders,order_id,ai-field-alex-g.demo_ecommerce.orders,ai-field-alex-g.demo_ecommerce.orders.order_id,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
6,oi,order_items,order_id,ai-field-alex-g.demo_ecommerce.order_items,ai-field-alex-g.demo_ecommerce.order_items.ord...,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
7,oi,order_items,product_id,ai-field-alex-g.demo_ecommerce.order_items,ai-field-alex-g.demo_ecommerce.order_items.pro...,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...
8,p,products,product_id,ai-field-alex-g.demo_ecommerce.products,ai-field-alex-g.demo_ecommerce.products.produc...,5207e6b0fe644251a1456568f465b2a760d2f03f05adc2...

In [14]:
test = sqlglot.parse_one(res["query_info"]["query"].iloc[0], read="bigquery")

In [96]:
table_expr = [x for x in test.find_all(Table)]
alias_to_table_name = dict()
alias_to_table_id = dict()
table_info = list()

table_ids = set()
for t in test.find_all(Table):
    table = t.this
    table_name = table.name
    table_alias = t.alias
    
    alias_to_table_name[table_alias or table_name] = table_name
    table_id = f"{t.catalog}.{t.db}.{table_name}"

    alias_to_table_id[table_alias or table_name] = table_id

    table_ids.add(table_id)
    table_info.append({
        "table_id": table_id,
        "table_name": table_name,
        "dataset_id": f"{t.catalog}.{t.db}",
        "database_id": t.catalog,
        "table_alias": table_alias
    })

print(table_ids)
print(alias_to_table_name)
tables_df = pd.DataFrame(table_info)
tables_df.head()

{'ai-field-alex-g.demo_ecommerce.products', 'ai-field-alex-g.demo_ecommerce.order_items', 'ai-field-alex-g.demo_ecommerce.orders'}
{'o': 'orders', 'oi': 'order_items', 'p': 'products'}

,table_id,table_name,dataset_id,database_id,table_alias
0,ai-field-alex-g.demo_ecommerce.orders,orders,ai-field-alex-g.demo_ecommerce,ai-field-alex-g,o
1,ai-field-alex-g.demo_ecommerce.order_items,order_items,ai-field-alex-g.demo_ecommerce,ai-field-alex-g,oi
2,ai-field-alex-g.demo_ecommerce.products,products,ai-field-alex-g.demo_ecommerce,ai-field-alex-g,p

In [91]:
[x for x in test.find_all(Column)][0]

Column(
  this=Identifier(this=order_id, quoted=False),
  table=Identifier(this=o, quoted=False))

In [97]:
columns = list()
for c in test.find_all(Column):
    table_alias = c.table
    table_name = alias_to_table_name.get(table_alias, table_alias)
    table_id = alias_to_table_id.get(table_alias, table_alias)
    column_name = c.this
    columns.append({
        "table_alias": table_alias,
        "table_name": table_name,
        "column_name": column_name,
        "table_id": table_id
    })
columns_df = pd.DataFrame(columns)
columns_df.head()

,table_alias,table_name,column_name,table_id
0,o,orders,order_id,ai-field-alex-g.demo_ecommerce.orders
1,oi,order_items,order_item_id,ai-field-alex-g.demo_ecommerce.order_items
2,p,products,product_name,ai-field-alex-g.demo_ecommerce.products
3,oi,order_items,quantity,ai-field-alex-g.demo_ecommerce.order_items
4,oi,order_items,price,ai-field-alex-g.demo_ecommerce.order_items

In [98]:

joins = []

for j in test.find_all(Join):
    left_table = j.this
    left_table_name = left_table.name
    left_table_alias = left_table.alias

    join_condition = j.args.get("on") if "on" in j.args else None

    if join_condition:
        right_table_alias = join_condition.this.table
        right_table_name = alias_to_table_name.get(right_table_alias, "?")
    else:
        right_table_name = None
        right_table_alias = None
    
    joins.append({
        "left_table": left_table_name, 
        "left_table_id": alias_to_table_id.get(left_table_alias, left_table_alias),
        "left_table_alias": left_table_alias,
        "left_column": join_condition.expression.this,
        "right_table": right_table_name, 
        "right_table_id": alias_to_table_id.get(right_table_alias, right_table_alias),
        "right_table_alias": right_table_alias,
        "right_column": join_condition.this.this,
        "criteria": str(join_condition)
        })

print(alias_to_table_name)
print()

{'o': 'orders', 'oi': 'order_items', 'p': 'products'}

In [99]:
joins_df = pd.DataFrame(joins)
joins_df.head()

,left_table,left_table_id,left_table_alias,left_column,right_table,right_table_id,right_table_alias,right_column,criteria
0,order_items,ai-field-alex-g.demo_ecommerce.order_items,oi,order_id,orders,ai-field-alex-g.demo_ecommerce.orders,o,order_id,o.order_id = oi.order_id
1,products,ai-field-alex-g.demo_ecommerce.products,p,product_id,order_items,ai-field-alex-g.demo_ecommerce.order_items,oi,product_id,oi.product_id = p.product_id

In [10]:
sql_table = parse_sql_query(res["query_info"]["query"].iloc[0], read="bigquery")

In [11]:
sql_table

{'query_text': 'SELECT o.order_id, oi.order_item_id, p.product_name, oi.quantity, oi.price\nFROM `ai-field-alex-g.demo_ecommerce.orders` AS o\nJOIN `ai-field-alex-g.demo_ecommerce.order_items` AS oi ON o.order_id = oi.order_id\nJOIN `ai-field-alex-g.demo_ecommerce.products` AS p ON oi.product_id = p.product_id;',
 'tables': ['orders', 'order_items', 'products'],
 'columns': [('order_items', 'price'),
  ('order_items', 'order_id'),
  ('products', 'product_id'),
  ('order_items', 'product_id'),
  ('order_items', 'quantity'),
  ('products', 'product_name'),
  ('orders', 'order_id'),
  ('order_items', 'order_item_id')],
 'join_criteria': 'JOIN order_items ON o.order_id = oi.order_id; JOIN products ON oi.product_id = p.product_id',
 'aliases': {'o': 'orders', 'oi': 'order_items', 'p': 'products'},
 'joins': [{'table': 'order_items', 'criteria': 'o.order_id = oi.order_id'},
  {'table': 'products', 'criteria': 'oi.product_id = p.product_id'}]}

In [12]:
pd.DataFrame(sql_table)

ValueError: All arrays must be of the same length